USE [AssessmentDb];
GO
SET NOCOUNT ON;
PRINT '======================================================================';
PRINT '  CARGA DE MALLAS CURRICULARES COMPLETAS (10 SEMESTRES) - 10 PROGRAMAS ';
PRINT '                 UNIVERSIDAD DEL MAGDALENA                            ';
PRINT '======================================================================';
GO

-- 1. Asegurar la columna ProgramaAcademicoId en la tabla Asignaturas
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'ProgramaAcademicoId' AND Object_ID = Object_ID(N'Asignaturas'))
BEGIN
    ALTER TABLE [Asignaturas] ADD [ProgramaAcademicoId] uniqueidentifier NULL;
    ALTER TABLE [Asignaturas] ADD CONSTRAINT [FK_Asignaturas_ProgramasAcademicos_ProgramaAcademicoId] 
        FOREIGN KEY ([ProgramaAcademicoId]) REFERENCES [ProgramasAcademicos] ([Id]);
END;
GO

-- 2. Sincronizar los 10 Programas Académicos
MERGE INTO [ProgramasAcademicos] AS Target
USING (VALUES
    ('ING-SIST', N'Ingeniería de Sistemas', N'Facultad de Ingeniería'),
    ('ING-CIVIL', N'Ingeniería Civil', N'Facultad de Ingeniería'),
    ('ING-IND', N'Ingeniería Industrial', N'Facultad de Ingeniería'),
    ('ING-ELEC', N'Ingeniería Electrónica', N'Facultad de Ingeniería'),
    ('ING-AMB', N'Ingeniería Ambiental y Sanitaria', N'Facultad de Ingeniería'),
    ('ING-AGRO', N'Ingeniería Agronómica', N'Facultad de Ingeniería'),
    ('ING-PESQ', N'Ingeniería Pesquera', N'Facultad de Ingeniería'),
    ('ING-MAR', N'Ingeniería Marino Costera', N'Facultad de Ingeniería'),
    ('ING-DATOS', N'Ingeniería en Ciencia de Datos', N'Facultad de Ingeniería'),
    ('ING-ENERG', N'Ingeniería Energética', N'Facultad de Ingeniería')
) AS Source ([Codigo], [Nombre], [Facultad])
ON (Target.[Codigo] = Source.[Codigo])
WHEN MATCHED THEN
    UPDATE SET Target.[Nombre] = Source.[Nombre], Target.[Facultad] = Source.[Facultad], Target.[EstaActivo] = 1
WHEN NOT MATCHED THEN
    INSERT ([Id], [Codigo], [Nombre], [Facultad], [FechaCreacion], [EstaActivo])
    VALUES (NEWID(), Source.[Codigo], Source.[Nombre], Source.[Facultad], GETUTCDATE(), 1);
GO

-- 3. Poblar tabla temporal con todas las asignaturas oficiales
CREATE TABLE #TempMallas (
    Codigo NVARCHAR(50),
    Nombre NVARCHAR(200),
    Creditos INT,
    Semestre INT,
    CodigoPrograma NVARCHAR(50)
);

-- ======================================================================
-- PROGRAMA: Ingeniería de Sistemas (ING-SIST) - Total: 52 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('SIS101', N'Introducción a la Ingeniería de Sistemas', 3, 1, 'ING-SIST'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-SIST'),
('MAT102', N'Álgebra Lineal', 3, 1, 'ING-SIST'),
('SIS102', N'Algoritmos y Lógica de Programación', 4, 1, 'ING-SIST'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-SIST'),
('ING101', N'Inglés I', 2, 1, 'ING-SIST'),
('SIS201', N'Programación Orientada a Objetos', 4, 2, 'ING-SIST'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-SIST'),
('FIS201', N'Física Mecánica', 4, 2, 'ING-SIST'),
('SIS202', N'Matemáticas Discretas', 3, 2, 'ING-SIST'),
('ING201', N'Inglés II', 2, 2, 'ING-SIST'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-SIST'),
('SIS301', N'Estructuras de Datos y Algoritmos', 4, 3, 'ING-SIST'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-SIST'),
('FIS301', N'Física de Campos y Ondas', 4, 3, 'ING-SIST'),
('SIS302', N'Organización y Arquitectura del Computador', 3, 3, 'ING-SIST'),
('EST301', N'Probabilidad y Estadística Fundamental', 3, 3, 'ING-SIST'),
('ING301', N'Inglés III', 2, 3, 'ING-SIST'),
('SIS401', N'Bases de Datos Relacionales', 4, 4, 'ING-SIST'),
('MAT401', N'Ecuaciones Diferenciales', 3, 4, 'ING-SIST'),
('SIS402', N'Análisis y Diseño de Software', 4, 4, 'ING-SIST'),
('SIS403', N'Sistemas Operativos y Concurrencia', 3, 4, 'ING-SIST'),
('SIS404', N'Teoría de la Computación y Lenguajes Formales', 3, 4, 'ING-SIST'),
('ING401', N'Inglés IV', 2, 4, 'ING-SIST'),
('SIS501', N'Ingeniería de Requisitos', 3, 5, 'ING-SIST'),
('SIS502', N'Arquitectura de Software y Patrones de Diseño', 4, 5, 'ING-SIST'),
('SIS503', N'Redes de Datos y Protocolos de Comunicación', 4, 5, 'ING-SIST'),
('SIS504', N'Bases de Datos Avanzadas y NoSQL', 3, 5, 'ING-SIST'),
('EST501', N'Estadística Aplicada e Inferencia', 3, 5, 'ING-SIST'),
('HUM501', N'Metodología de la Investigación Científica', 2, 5, 'ING-SIST'),
('SIS601', N'Desarrollo Web Fullstack y Cloud', 4, 6, 'ING-SIST'),
('SIS602', N'Pruebas y Aseguramiento de la Calidad del Software', 4, 6, 'ING-SIST'),
('SIS603', N'Seguridad de la Información y Criptografía', 3, 6, 'ING-SIST'),
('SIS604', N'Sistemas Distribuidos y Microservicios', 3, 6, 'ING-SIST'),
('ECO601', N'Ingeniería Económica y Finanzas', 3, 6, 'ING-SIST'),
('SIS701', N'Desarrollo de Aplicaciones Móviles', 4, 7, 'ING-SIST'),
('SIS702', N'Gestión de Proyectos de TI (Metodologías Ágiles)', 3, 7, 'ING-SIST'),
('SIS703', N'Inteligencia Artificial y Aprendizaje Automático', 4, 7, 'ING-SIST'),
('SIS704', N'Electiva de Profundización I - Sistemas', 3, 7, 'ING-SIST'),
('HUM701', N'Ética Profesional y Legislación Informática', 2, 7, 'ING-SIST'),
('SIS801', N'Computación en la Nube y DevOps', 4, 8, 'ING-SIST'),
('SIS802', N'Analítica de Datos y Big Data', 4, 8, 'ING-SIST'),
('SIS803', N'Internet de las Cosas (IoT) y Sistemas Embebidos', 3, 8, 'ING-SIST'),
('SIS804', N'Electiva de Profundización II - Sistemas', 3, 8, 'ING-SIST'),
('HUM801', N'Formulación y Evaluación de Proyectos', 3, 8, 'ING-SIST'),
('SIS901', N'Proyecto de Grado I - Sistemas', 4, 9, 'ING-SIST'),
('SIS902', N'Gobierno de TI y Auditoría de Sistemas', 3, 9, 'ING-SIST'),
('SIS903', N'Electiva de Profundización III - Sistemas', 3, 9, 'ING-SIST'),
('SIS904', N'Electiva Complementaria de Humanidades', 2, 9, 'ING-SIST'),
('SIS1001', N'Proyecto de Grado II - Sistemas', 4, 10, 'ING-SIST'),
('SIS1002', N'Práctica Profesional en Ingeniería de Sistemas', 6, 10, 'ING-SIST'),
('SIS1003', N'Innovación y Emprendimiento de Base Tecnológica', 3, 10, 'ING-SIST');

-- ======================================================================
-- PROGRAMA: Ingeniería Civil (ING-CIVIL) - Total: 49 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('CIV101', N'Introducción a la Ingeniería Civil', 3, 1, 'ING-CIVIL'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-CIVIL'),
('MAT102', N'Álgebra Lineal', 3, 1, 'ING-CIVIL'),
('CIV102', N'Dibujo en Ingeniería y CAD', 3, 1, 'ING-CIVIL'),
('QUI101', N'Química General para Ingenieros', 3, 1, 'ING-CIVIL'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-CIVIL'),
('CIV201', N'Topografía y Planimetría', 4, 2, 'ING-CIVIL'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-CIVIL'),
('FIS201', N'Física Mecánica y Laboratorio', 4, 2, 'ING-CIVIL'),
('CIV202', N'Geología General y Geotecnia', 3, 2, 'ING-CIVIL'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-CIVIL'),
('CIV301', N'Estática y Dinámica de Estructuras', 4, 3, 'ING-CIVIL'),
('CIV302', N'Altimetría y Topografía de Vías', 3, 3, 'ING-CIVIL'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-CIVIL'),
('FIS301', N'Física de Campos y Termodinámica', 4, 3, 'ING-CIVIL'),
('CIV303', N'Materiales de Construcción y Concretos', 3, 3, 'ING-CIVIL'),
('CIV401', N'Resistencia de Materiales I', 4, 4, 'ING-CIVIL'),
('CIV402', N'Mecánica de Fluidos', 4, 4, 'ING-CIVIL'),
('MAT401', N'Ecuaciones Diferenciales', 3, 4, 'ING-CIVIL'),
('EST301', N'Probabilidad y Estadística Fundamental', 3, 4, 'ING-CIVIL'),
('CIV403', N'Sistemas de Información Geográfica (SIG)', 3, 4, 'ING-CIVIL'),
('CIV501', N'Resistencia de Materiales II', 3, 5, 'ING-CIVIL'),
('CIV502', N'Mecánica de Suelos I', 4, 5, 'ING-CIVIL'),
('CIV503', N'Hidráulica de Canales y Tuberías', 4, 5, 'ING-CIVIL'),
('CIV504', N'Análisis Estructural I', 4, 5, 'ING-CIVIL'),
('ECO601', N'Ingeniería Económica', 3, 5, 'ING-CIVIL'),
('CIV601', N'Análisis Estructural II', 4, 6, 'ING-CIVIL'),
('CIV602', N'Mecánica de Suelos II y Cimentaciones', 4, 6, 'ING-CIVIL'),
('CIV603', N'Hidrología y Climatología Aplicada', 3, 6, 'ING-CIVIL'),
('CIV604', N'Diseño Geométrico de Vías', 4, 6, 'ING-CIVIL'),
('CIV605', N'Procedimientos y Procesos Constructivos', 3, 6, 'ING-CIVIL'),
('CIV701', N'Diseño de Estructuras de Concreto Reforzado', 4, 7, 'ING-CIVIL'),
('CIV702', N'Ingeniería de Tránsito y Transporte', 3, 7, 'ING-CIVIL'),
('CIV703', N'Acueductos, Alcantarillados y Drenajes', 4, 7, 'ING-CIVIL'),
('CIV704', N'Pavimentos Asfálticos y Rígidos', 4, 7, 'ING-CIVIL'),
('CIV705', N'Electiva de Profundización I - Civil', 3, 7, 'ING-CIVIL'),
('CIV801', N'Diseño de Estructuras Metálicas', 4, 8, 'ING-CIVIL'),
('CIV802', N'Obras Hidráulicas y Presas', 4, 8, 'ING-CIVIL'),
('CIV803', N'Costos, Presupuestos y Programación de Obras', 3, 8, 'ING-CIVIL'),
('CIV804', N'Electiva de Profundización II - Civil', 3, 8, 'ING-CIVIL'),
('HUM801', N'Formulación y Evaluación de Proyectos', 3, 8, 'ING-CIVIL'),
('CIV901', N'Proyecto de Grado I - Civil', 4, 9, 'ING-CIVIL'),
('CIV902', N'Interventoría y Supervisión Técnica de Obras', 3, 9, 'ING-CIVIL'),
('CIV903', N'Impacto Ambiental en Obras Civiles', 3, 9, 'ING-CIVIL'),
('CIV904', N'Electiva de Profundización III - Civil', 3, 9, 'ING-CIVIL'),
('HUM701', N'Ética Profesional y Legislación de la Construcción', 2, 9, 'ING-CIVIL'),
('CIV1001', N'Proyecto de Grado II - Civil', 4, 10, 'ING-CIVIL'),
('CIV1002', N'Práctica Profesional en Ingeniería Civil', 6, 10, 'ING-CIVIL'),
('CIV1003', N'Gestión Integral del Riesgo en Infraestructura', 3, 10, 'ING-CIVIL');

-- ======================================================================
-- PROGRAMA: Ingeniería Industrial (ING-IND) - Total: 48 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('IND101', N'Introducción a la Ingeniería Industrial', 3, 1, 'ING-IND'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-IND'),
('MAT102', N'Álgebra Lineal', 3, 1, 'ING-IND'),
('QUI101', N'Química General e Industrial', 3, 1, 'ING-IND'),
('IND102', N'Dibujo Técnico y CAD Industrial', 3, 1, 'ING-IND'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-IND'),
('IND201', N'Estudio del Trabajo y Tiempos', 4, 2, 'ING-IND'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-IND'),
('FIS201', N'Física Mecánica', 4, 2, 'ING-IND'),
('IND202', N'Procesos Industriales y Materiales', 3, 2, 'ING-IND'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-IND'),
('IND301', N'Diseño de Procesos Productivos', 4, 3, 'ING-IND'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-IND'),
('FIS301', N'Física de Campos y Termodinámica', 4, 3, 'ING-IND'),
('EST301', N'Probabilidad y Estadística Fundamental', 3, 3, 'ING-IND'),
('ADM301', N'Fundamentos de Administración y Organizaciones', 3, 3, 'ING-IND'),
('IND401', N'Investigación de Operaciones I (Determinística)', 4, 4, 'ING-IND'),
('IND402', N'Control Estadístico de la Calidad', 4, 4, 'ING-IND'),
('MAT401', N'Ecuaciones Diferenciales', 3, 4, 'ING-IND'),
('IND403', N'Contabilidad de Costos Industriales', 3, 4, 'ING-IND'),
('EST501', N'Estadística Aplicada e Inferencia', 3, 4, 'ING-IND'),
('IND501', N'Investigación de Operaciones II (Estocástica)', 4, 5, 'ING-IND'),
('IND502', N'Gestión de la Producción y Operaciones I', 4, 5, 'ING-IND'),
('IND503', N'Ergonomía y Seguridad Industrial (SST)', 3, 5, 'ING-IND'),
('ECO601', N'Ingeniería Económica', 3, 5, 'ING-IND'),
('IND504', N'Mantenimiento Industrial y Confiabilidad', 3, 5, 'ING-IND'),
('IND601', N'Gestión de la Producción y Operaciones II', 4, 6, 'ING-IND'),
('IND602', N'Logística Empresarial y Gestión de Inventarios', 4, 6, 'ING-IND'),
('IND603', N'Diseño y Distribución de Plantas Industriales', 4, 6, 'ING-IND'),
('IND604', N'Gestión de Sistemas de Calidad Integrados', 3, 6, 'ING-IND'),
('IND605', N'Modelado y Simulación de Procesos', 3, 6, 'ING-IND'),
('IND701', N'Gestión de la Cadena de Suministro (SCM)', 4, 7, 'ING-IND'),
('IND702', N'Ingeniería y Gestión Ambiental en Industrias', 3, 7, 'ING-IND'),
('IND703', N'Mercadeo Industrial y Gestión Comercial', 3, 7, 'ING-IND'),
('IND704', N'Electiva de Profundización I - Industrial', 3, 7, 'ING-IND'),
('HUM701', N'Ética Profesional y Responsabilidad Social', 2, 7, 'ING-IND'),
('IND801', N'Automatización y Robótica de Procesos', 4, 8, 'ING-IND'),
('IND802', N'Dirección Estratégica y Toma de Decisiones', 3, 8, 'ING-IND'),
('IND803', N'Formulación y Evaluación de Proyectos Industriales', 4, 8, 'ING-IND'),
('IND804', N'Electiva de Profundización II - Industrial', 3, 8, 'ING-IND'),
('IND805', N'Analítica de Operaciones y Big Data', 3, 8, 'ING-IND'),
('IND901', N'Proyecto de Grado I - Industrial', 4, 9, 'ING-IND'),
('IND902', N'Optimización de Procesos y Lean Six Sigma', 4, 9, 'ING-IND'),
('IND903', N'Electiva de Profundización III - Industrial', 3, 9, 'ING-IND'),
('IND904', N'Electiva Complementaria Humanidades', 2, 9, 'ING-IND'),
('IND1001', N'Proyecto de Grado II - Industrial', 4, 10, 'ING-IND'),
('IND1002', N'Práctica Profesional en Ingeniería Industrial', 6, 10, 'ING-IND'),
('IND1003', N'Innovación, Emprendimiento y Modelos de Negocio', 3, 10, 'ING-IND');

-- ======================================================================
-- PROGRAMA: Ingeniería Agronómica (ING-AGRO) - Total: 49 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('AGR101', N'Introducción a las Ciencias Agronómicas', 3, 1, 'ING-AGRO'),
('AGR102', N'Botánica General y Morfología Vegetal', 4, 1, 'ING-AGRO'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-AGRO'),
('QUI101', N'Química General e Inorgánica', 3, 1, 'ING-AGRO'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-AGRO'),
('ING101', N'Inglés I', 2, 1, 'ING-AGRO'),
('AGR201', N'Botánica Sistemática y Taxonomía Vegetal', 4, 2, 'ING-AGRO'),
('AGR202', N'Química Orgánica y Bioquímica Agrícola', 4, 2, 'ING-AGRO'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-AGRO'),
('FIS201', N'Física Aplicada a la Agronomía', 4, 2, 'ING-AGRO'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-AGRO'),
('AGR301', N'Fisiología Vegetal', 4, 3, 'ING-AGRO'),
('AGR302', N'Edafología, Génesis y Clasificación de Suelos', 4, 3, 'ING-AGRO'),
('AGR303', N'Microbiología Agrícola y de Suelos', 3, 3, 'ING-AGRO'),
('EST301', N'Probabilidad y Diseños Experimentales', 4, 3, 'ING-AGRO'),
('AGR304', N'Topografía Agrícola y Manejo de Tierras', 3, 3, 'ING-AGRO'),
('AGR401', N'Nutrición Vegetal y Fertilidad de Suelos', 4, 4, 'ING-AGRO'),
('AGR402', N'Entomología General y de Insectos Plaga', 4, 4, 'ING-AGRO'),
('AGR403', N'Agrometeorología y Clima Tropical', 3, 4, 'ING-AGRO'),
('AGR404', N'Genética General y Vegetal', 4, 4, 'ING-AGRO'),
('AGR405', N'Mapeo Digital y SIG Agrícola', 3, 4, 'ING-AGRO'),
('AGR501', N'Fitopatología y Enfermedades de Cultivos', 4, 5, 'ING-AGRO'),
('AGR502', N'Riegos, Drenajes y Manejo de Recursos Hídricos', 4, 5, 'ING-AGRO'),
('AGR503', N'Maquinaria, Mecanización y Fuentes de Potencia', 3, 5, 'ING-AGRO'),
('AGR504', N'Fisiología de la Producción Agrícola', 3, 5, 'ING-AGRO'),
('ECO601', N'Economía Agraria', 3, 5, 'ING-AGRO'),
('AGR601', N'Manejo Integrado de Plagas (MIP)', 4, 6, 'ING-AGRO'),
('AGR602', N'Fitomejoramiento y Biotecnología Vegetal', 4, 6, 'ING-AGRO'),
('AGR603', N'Propagación de Plantas, Semillas y Viveros', 3, 6, 'ING-AGRO'),
('AGR604', N'Manejo Integrado de Malezas y Arvenses', 3, 6, 'ING-AGRO'),
('AGR605', N'Agroecología y Sistemas de Producción Sostenible', 3, 6, 'ING-AGRO'),
('AGR701', N'Sistemas de Cultivos de Clima Cálido (Palma, Banano, Café)', 4, 7, 'ING-AGRO'),
('AGR702', N'Agroforestería, Silvopastoreo y Conservación de Suelos', 3, 7, 'ING-AGRO'),
('AGR703', N'Sistemas de Producción de Hortalizas y Frutales', 4, 7, 'ING-AGRO'),
('AGR704', N'Electiva de Profundización I - Agronomía', 3, 7, 'ING-AGRO'),
('HUM701', N'Legislación Agraria y Ambiental', 2, 7, 'ING-AGRO'),
('AGR801', N'Fisiología y Tecnología de Poscosecha', 4, 8, 'ING-AGRO'),
('AGR802', N'Administración y Gestión de Empresas Agropecuarias', 3, 8, 'ING-AGRO'),
('AGR803', N'Agricultura de Precisión, Sensores y Drones', 3, 8, 'ING-AGRO'),
('AGR804', N'Electiva de Profundización II - Agronomía', 3, 8, 'ING-AGRO'),
('HUM801', N'Formulación y Evaluación de Proyectos Agropecuarios', 3, 8, 'ING-AGRO'),
('AGR901', N'Proyecto de Grado I - Agronomía', 4, 9, 'ING-AGRO'),
('AGR902', N'Inocuidad, BPA y Certificaciones Agrícolas', 3, 9, 'ING-AGRO'),
('AGR903', N'Comercialización y Cadenas de Valor Agropecuarias', 3, 9, 'ING-AGRO'),
('AGR904', N'Electiva de Profundización III - Agronomía', 3, 9, 'ING-AGRO'),
('HUM901', N'Ética Profesional y Desarrollo Rural Sostenible', 2, 9, 'ING-AGRO'),
('AGR1001', N'Proyecto de Grado II - Agronomía', 4, 10, 'ING-AGRO'),
('AGR1002', N'Práctica Profesional en Ingeniería Agronómica', 6, 10, 'ING-AGRO'),
('AGR1003', N'Extensión Rural y Transferencia Tecnológica', 3, 10, 'ING-AGRO');

-- ======================================================================
-- PROGRAMA: Ingeniería Pesquera (ING-PESQ) - Total: 49 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('PES101', N'Introducción a las Ciencias Pesqueras', 3, 1, 'ING-PESQ'),
('PES102', N'Biología Marina y de Recursos Acuáticos', 4, 1, 'ING-PESQ'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-PESQ'),
('QUI101', N'Química General e Inorgánica', 3, 1, 'ING-PESQ'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-PESQ'),
('ING101', N'Inglés I', 2, 1, 'ING-PESQ'),
('PES201', N'Ictiología y Taxonomía de Peces y Crustáceos', 4, 2, 'ING-PESQ'),
('PES202', N'Química Orgánica y Bioquímica Acuática', 4, 2, 'ING-PESQ'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-PESQ'),
('FIS201', N'Física Mecánica y de Fluidos', 4, 2, 'ING-PESQ'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-PESQ'),
('PES301', N'Ecología Acuática y Limnología', 4, 3, 'ING-PESQ'),
('PES302', N'Oceanografía Física y Pesquera', 4, 3, 'ING-PESQ'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-PESQ'),
('EST301', N'Bioestadística y Diseños Experimentales', 4, 3, 'ING-PESQ'),
('PES303', N'Navegación, Cartografía y Comunicaciones Marítimas', 3, 3, 'ING-PESQ'),
('PES401', N'Acuicultura General y Sistemas de Cultivo', 4, 4, 'ING-PESQ'),
('PES402', N'Tecnología de Materiales y Artes de Pesca', 4, 4, 'ING-PESQ'),
('PES403', N'Dinámica de Poblaciones y Evaluación de Stocks', 4, 4, 'ING-PESQ'),
('PES404', N'Fisiología y Nutrición de Organismos Acuáticos', 3, 4, 'ING-PESQ'),
('EST501', N'Modelación Estadística Pesquera', 3, 4, 'ING-PESQ'),
('PES501', N'Piscicultura Continental y Marina', 4, 5, 'ING-PESQ'),
('PES502', N'Embarcaciones Pesqueras y Máquinas Marinas', 4, 5, 'ING-PESQ'),
('PES503', N'Calidad de Aguas y Tratamiento de Efluentes Acuícolas', 3, 5, 'ING-PESQ'),
('PES504', N'Patología y Sanidad Acuícola', 3, 5, 'ING-PESQ'),
('ECO601', N'Economía Pesquera y de Recursos Marinos', 3, 5, 'ING-PESQ'),
('PES601', N'Cultivo de Moluscos y Crustáceos', 4, 6, 'ING-PESQ'),
('PES602', N'Microbiología y Análisis de Alimentos Acuáticos', 4, 6, 'ING-PESQ'),
('PES603', N'Operaciones y Métodos de Pesca Industrial y Artesanal', 4, 6, 'ING-PESQ'),
('PES604', N'Diseño e Ingeniería de Plantas e Instalaciones Acuícolas', 3, 6, 'ING-PESQ'),
('PES605', N'Manejo y Preservación de Recursos Vivos en Alta Mar', 3, 6, 'ING-PESQ'),
('PES701', N'Tecnología y Procesamiento de Productos Pesqueros', 4, 7, 'ING-PESQ'),
('PES702', N'Control y Aseguramiento de Calidad (HACCP Pesquero)', 4, 7, 'ING-PESQ'),
('PES703', N'Manejo y Ordenamiento de Pesquerías Sostenibles', 3, 7, 'ING-PESQ'),
('PES704', N'Electiva de Profundización I - Pesquera', 3, 7, 'ING-PESQ'),
('HUM701', N'Legislación y Políticas Pesqueras y Marítimas', 2, 7, 'ING-PESQ'),
('PES801', N'Biotecnología y Genética Aplicada a la Acuicultura', 4, 8, 'ING-PESQ'),
('PES802', N'Administración y Gestión de Empresas Pesqueras', 3, 8, 'ING-PESQ'),
('PES803', N'Desarrollo e Innovación de Nuevos Productos Marinos', 3, 8, 'ING-PESQ'),
('PES804', N'Electiva de Profundización II - Pesquera', 3, 8, 'ING-PESQ'),
('HUM801', N'Formulación y Evaluación de Proyectos Acuícolas', 3, 8, 'ING-PESQ'),
('PES901', N'Proyecto de Grado I - Pesquera', 4, 9, 'ING-PESQ'),
('PES902', N'Comercio Internacional y Logística de Cadena de Frío', 3, 9, 'ING-PESQ'),
('PES903', N'Impacto Ambiental y Certificaciones Pesqueras', 3, 9, 'ING-PESQ'),
('PES904', N'Electiva de Profundización III - Pesquera', 3, 9, 'ING-PESQ'),
('HUM901', N'Ética Profesional y Gobernanza Marina', 2, 9, 'ING-PESQ'),
('PES1001', N'Proyecto de Grado II - Pesquera', 4, 10, 'ING-PESQ'),
('PES1002', N'Práctica Profesional en Ingeniería Pesquera', 6, 10, 'ING-PESQ'),
('PES1003', N'Emprendimiento e Innovación en Bioeconomía Azul', 3, 10, 'ING-PESQ');

-- ======================================================================
-- PROGRAMA: Ingeniería Ambiental y Sanitaria (ING-AMB) - Total: 49 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('AMB101', N'Introducción a la Ingeniería Ambiental y Sanitaria', 3, 1, 'ING-AMB'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-AMB'),
('MAT102', N'Álgebra Lineal', 3, 1, 'ING-AMB'),
('QUI101', N'Química General e Inorgánica', 3, 1, 'ING-AMB'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-AMB'),
('AMB102', N'Biología y Ecología General', 3, 1, 'ING-AMB'),
('AMB201', N'Química Ambiental y Sanitaria', 4, 2, 'ING-AMB'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-AMB'),
('FIS201', N'Física Mecánica y Termodinámica', 4, 2, 'ING-AMB'),
('AMB202', N'Geología Ambiental y Geomorfología', 3, 2, 'ING-AMB'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-AMB'),
('AMB301', N'Microbiología Ambiental y de Aguas', 4, 3, 'ING-AMB'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-AMB'),
('FIS301', N'Física de Fluidos y Transporte de Masa', 4, 3, 'ING-AMB'),
('EST301', N'Estadística y Muestreo Ambiental', 3, 3, 'ING-AMB'),
('AMB302', N'Topografía y Cartografía Digital', 3, 3, 'ING-AMB'),
('AMB401', N'Mecánica de Fluidos e Hidráulica Ambiental', 4, 4, 'ING-AMB'),
('MAT401', N'Ecuaciones Diferenciales', 3, 4, 'ING-AMB'),
('AMB402', N'Hidrología y Manejo de Cuencas Hidrográficas', 4, 4, 'ING-AMB'),
('AMB403', N'Sistemas de Información Geográfica Aplicados (SIG)', 3, 4, 'ING-AMB'),
('AMB404', N'Climatología y Meteorología de Contaminantes', 3, 4, 'ING-AMB'),
('AMB501', N'Calidad del Agua y Parámetros Fisicoquímicos', 4, 5, 'ING-AMB'),
('AMB502', N'Diseño de Redes de Acueductos y Alcantarillados', 4, 5, 'ING-AMB'),
('AMB503', N'Operaciones Unitarias en Ingeniería Ambiental', 4, 5, 'ING-AMB'),
('AMB504', N'Contaminación y Química del Suelo', 3, 5, 'ING-AMB'),
('ECO601', N'Economía Ambiental y Valoración Económica', 3, 5, 'ING-AMB'),
('AMB601', N'Plantas de Tratamiento de Agua Potable (PTAP)', 4, 6, 'ING-AMB'),
('AMB602', N'Plantas de Tratamiento de Aguas Residuales (PTAR)', 4, 6, 'ING-AMB'),
('AMB603', N'Gestión Integral de Residuos Sólidos Urbanos', 4, 6, 'ING-AMB'),
('AMB604', N'Calidad del Aire, Emisiones y Control de Ruido', 3, 6, 'ING-AMB'),
('AMB605', N'Modelación y Simulación Ambiental', 3, 6, 'ING-AMB'),
('AMB701', N'Evaluación de Impacto Ambiental (EIA)', 4, 7, 'ING-AMB'),
('AMB702', N'Manejo de Residuos Peligrosos y Especiales (RESPEL)', 3, 7, 'ING-AMB'),
('AMB703', N'Biorremediación y Restauración Ecológica', 3, 7, 'ING-AMB'),
('AMB704', N'Electiva de Profundización I - Ambiental', 3, 7, 'ING-AMB'),
('HUM701', N'Legislación y Normatividad Ambiental Colombiana', 2, 7, 'ING-AMB'),
('AMB801', N'Sistemas de Gestión Ambiental (ISO 14001) y Huella de Carbono', 4, 8, 'ING-AMB'),
('AMB802', N'Salud Pública, Epidemiología y Toxicología Ambiental', 3, 8, 'ING-AMB'),
('AMB803', N'Energías Renovables y Mitigación de Cambio Climático', 3, 8, 'ING-AMB'),
('AMB804', N'Electiva de Profundización II - Ambiental', 3, 8, 'ING-AMB'),
('HUM801', N'Formulación y Evaluación de Proyectos Ambientales', 3, 8, 'ING-AMB'),
('AMB901', N'Proyecto de Grado I - Ambiental y Sanitaria', 4, 9, 'ING-AMB'),
('AMB902', N'Auditoría Ambiental y Producción Más Limpia', 3, 9, 'ING-AMB'),
('AMB903', N'Gestión del Riesgo y Adaptación al Cambio Climático', 3, 9, 'ING-AMB'),
('AMB904', N'Electiva de Profundización III - Ambiental', 3, 9, 'ING-AMB'),
('HUM901', N'Ética Ambiental y Responsabilidad Socioambiental', 2, 9, 'ING-AMB'),
('AMB1001', N'Proyecto de Grado II - Ambiental y Sanitaria', 4, 10, 'ING-AMB'),
('AMB1002', N'Práctica Profesional en Ingeniería Ambiental', 6, 10, 'ING-AMB'),
('AMB1003', N'Ecoinnovación y Negocios Verdes', 3, 10, 'ING-AMB');

-- ======================================================================
-- PROGRAMA: Ingeniería Electrónica (ING-ELEC) - Total: 49 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('ELE101', N'Introducción a la Ingeniería Electrónica', 3, 1, 'ING-ELEC'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-ELEC'),
('MAT102', N'Álgebra Lineal', 3, 1, 'ING-ELEC'),
('ELE102', N'Algoritmos y Programación para Ingeniería', 3, 1, 'ING-ELEC'),
('QUI101', N'Química General para Ingenieros', 3, 1, 'ING-ELEC'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-ELEC'),
('ELE201', N'Circuitos Eléctricos I', 4, 2, 'ING-ELEC'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-ELEC'),
('FIS201', N'Física Mecánica y Oscilaciones', 4, 2, 'ING-ELEC'),
('ELE202', N'Diseño Digital y Lógica Booleana', 4, 2, 'ING-ELEC'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-ELEC'),
('ELE301', N'Circuitos Eléctricos II y Corriente Alterna', 4, 3, 'ING-ELEC'),
('ELE302', N'Dispositivos Semiconductores y Diodos', 4, 3, 'ING-ELEC'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-ELEC'),
('FIS301', N'Electromagnetismo y Teoría de Campos', 4, 3, 'ING-ELEC'),
('ELE303', N'Sistemas Digitales y VHDL/FPGA', 3, 3, 'ING-ELEC'),
('ELE401', N'Electrónica Analógica I (Transistores y Amplificadores)', 4, 4, 'ING-ELEC'),
('ELE402', N'Microprocesadores, Microcontroladores y Arquitectura', 4, 4, 'ING-ELEC'),
('MAT401', N'Ecuaciones Diferenciales y Transformadas', 3, 4, 'ING-ELEC'),
('ELE403', N'Señales y Sistemas Continuos', 3, 4, 'ING-ELEC'),
('EST301', N'Probabilidad y Procesos Estocásticos', 3, 4, 'ING-ELEC'),
('ELE501', N'Electrónica Analógica II (OpAmps y Filtros)', 4, 5, 'ING-ELEC'),
('ELE502', N'Sistemas de Control Clásico y Modelado', 4, 5, 'ING-ELEC'),
('ELE503', N'Procesamiento Digital de Señales (DSP)', 4, 5, 'ING-ELEC'),
('ELE504', N'Electrónica de Potencia y Convertidores', 3, 5, 'ING-ELEC'),
('ECO601', N'Ingeniería Económica', 3, 5, 'ING-ELEC'),
('ELE601', N'Sistemas de Control Digital y Moderno', 4, 6, 'ING-ELEC'),
('ELE602', N'Líneas de Transmisión y Antenas', 4, 6, 'ING-ELEC'),
('ELE603', N'Sistemas de Comunicaciones Analógicas y Digitales', 4, 6, 'ING-ELEC'),
('ELE604', N'Instrumentación Electrónica y Sensores', 3, 6, 'ING-ELEC'),
('ELE605', N'Diseño de Circuitos Impresos (PCB) y Prototipado', 3, 6, 'ING-ELEC'),
('ELE701', N'Automatización Industrial, PLC y SCADA', 4, 7, 'ING-ELEC'),
('ELE702', N'Comunicaciones Ópticas e Inalámbricas', 4, 7, 'ING-ELEC'),
('ELE703', N'Sistemas Embebidos y RTOS', 3, 7, 'ING-ELEC'),
('ELE704', N'Electiva de Profundización I - Electrónica', 3, 7, 'ING-ELEC'),
('HUM701', N'Ética Profesional y Marco Regulatorio TIC', 2, 7, 'ING-ELEC'),
('ELE801', N'Robótica Industrial y Visión Artificial', 4, 8, 'ING-ELEC'),
('ELE802', N'Redes de Sensores e Internet de las Cosas (IoT)', 4, 8, 'ING-ELEC'),
('ELE803', N'Sistemas Biomédicos y Bioinstrumentación', 3, 8, 'ING-ELEC'),
('ELE804', N'Electiva de Profundización II - Electrónica', 3, 8, 'ING-ELEC'),
('HUM801', N'Formulación y Evaluación de Proyectos Electrónicos', 3, 8, 'ING-ELEC'),
('ELE901', N'Proyecto de Grado I - Electrónica', 4, 9, 'ING-ELEC'),
('ELE902', N'Compatibilidad Electromagnética (EMC) y Normas', 3, 9, 'ING-ELEC'),
('ELE903', N'Vehículos Autónomos y Drones', 3, 9, 'ING-ELEC'),
('ELE904', N'Electiva de Profundización III - Electrónica', 3, 9, 'ING-ELEC'),
('HUM901', N'Innovación y Transferencia de Tecnología', 2, 9, 'ING-ELEC'),
('ELE1001', N'Proyecto de Grado II - Electrónica', 4, 10, 'ING-ELEC'),
('ELE1002', N'Práctica Profesional en Ingeniería Electrónica', 6, 10, 'ING-ELEC'),
('ELE1003', N'Gestión de Mantenimiento Electrónico y Calibración', 3, 10, 'ING-ELEC');

-- ======================================================================
-- PROGRAMA: Ingeniería Marino Costera (ING-MAR) - Total: 49 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('MAR101', N'Introducción a la Ingeniería Marino Costera', 3, 1, 'ING-MAR'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-MAR'),
('MAT102', N'Álgebra Lineal', 3, 1, 'ING-MAR'),
('QUI101', N'Química Marina y Soluciones', 3, 1, 'ING-MAR'),
('MAR102', N'Dibujo Técnico y Cartografía Náutica', 3, 1, 'ING-MAR'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-MAR'),
('MAR201', N'Geología Marina y Geomorfología Litoral', 4, 2, 'ING-MAR'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-MAR'),
('FIS201', N'Física Mecánica y Ondulatoria', 4, 2, 'ING-MAR'),
('MAR202', N'Biología y Ecosistemas Marinos Costeros', 3, 2, 'ING-MAR'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-MAR'),
('MAR301', N'Oceanografía Física y Dinámica Marina', 4, 3, 'ING-MAR'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-MAR'),
('FIS301', N'Mecánica de Fluidos Marinos', 4, 3, 'ING-MAR'),
('EST301', N'Estadística de Variables Hidro-Oceanográficas', 3, 3, 'ING-MAR'),
('MAR302', N'Topografía y Batimetría Costera', 3, 3, 'ING-MAR'),
('MAR401', N'Hidrodinámica Marina y Teoría de Olas', 4, 4, 'ING-MAR'),
('MAT401', N'Ecuaciones Diferenciales', 3, 4, 'ING-MAR'),
('MAR402', N'Mecánica de Suelos Marinos y Sedimentos', 4, 4, 'ING-MAR'),
('MAR403', N'Sistemas de Información Geográfica Marina (SIG-M)', 3, 4, 'ING-MAR'),
('MAR404', N'Meteorología Marina y Climatología Extrema', 3, 4, 'ING-MAR'),
('MAR501', N'Dinámica del Oleaje, Mareas y Corrientes Litorales', 4, 5, 'ING-MAR'),
('MAR502', N'Transporte de Sedimentos y Morfodinámica de Playas', 4, 5, 'ING-MAR'),
('MAR503', N'Materiales para Ambientes Marinos y Corrosión', 3, 5, 'ING-MAR'),
('MAR504', N'Operaciones Unitarias y Desalación de Agua', 3, 5, 'ING-MAR'),
('ECO601', N'Ingeniería Económica Marina', 3, 5, 'ING-MAR'),
('MAR601', N'Diseño de Obras de Protección Costera (Espigones, Tajamares)', 4, 6, 'ING-MAR'),
('MAR602', N'Ingeniería Portuaria, Muelles y Terminales Marítimas', 4, 6, 'ING-MAR'),
('MAR603', N'Modelación Numérica Hidrodinámica y de Sedimentos', 4, 6, 'ING-MAR'),
('MAR604', N'Estructuras Offshore y Plataformas Marinas', 3, 6, 'ING-MAR'),
('MAR605', N'Dragados, Rellenos y Gestión de Canales Navegables', 3, 6, 'ING-MAR'),
('MAR701', N'Manejo Integrado de Zonas Costeras (MIZC)', 4, 7, 'ING-MAR'),
('MAR702', N'Evaluación de Impacto Ambiental en Proyectos Marinos', 3, 7, 'ING-MAR'),
('MAR703', N'Energías Marinas Renovables (Undimotriz y Mareomotriz)', 4, 7, 'ING-MAR'),
('MAR704', N'Electiva de Profundización I - Marino Costera', 3, 7, 'ING-MAR'),
('HUM701', N'Derecho Marítimo Internacional y Legislación Costera', 2, 7, 'ING-MAR'),
('MAR801', N'Riesgos Costeros, Erosión Litoral y Alerta Temprana', 4, 8, 'ING-MAR'),
('MAR802', N'Planificación y Operación Portuaria y Logística', 3, 8, 'ING-MAR'),
('MAR803', N'Diseño de Emisarios Submarinos y Obras de Descarga', 3, 8, 'ING-MAR'),
('MAR804', N'Electiva de Profundización II - Marino Costera', 3, 8, 'ING-MAR'),
('HUM801', N'Formulación y Evaluación de Proyectos Portuarios y Costeros', 3, 8, 'ING-MAR'),
('MAR901', N'Proyecto de Grado I - Marino Costera', 4, 9, 'ING-MAR'),
('MAR902', N'Restauración Ecológica de Playas y Arrecifes', 3, 9, 'ING-MAR'),
('MAR903', N'Inspección Subacuática, Buceo y Robótica Marina (ROVs)', 3, 9, 'ING-MAR'),
('MAR904', N'Electiva de Profundización III - Marino Costera', 3, 9, 'ING-MAR'),
('HUM901', N'Ética Profesional y Gobernanza Oceánica', 2, 9, 'ING-MAR'),
('MAR1001', N'Proyecto de Grado II - Marino Costera', 4, 10, 'ING-MAR'),
('MAR1002', N'Práctica Profesional en Ingeniería Marino Costera', 6, 10, 'ING-MAR'),
('MAR1003', N'Innovación en Infraestructura Resiliente Costera', 3, 10, 'ING-MAR');

-- ======================================================================
-- PROGRAMA: Ingeniería en Ciencia de Datos (ING-DATOS) - Total: 48 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('DAT101', N'Introducción a la Ciencia de Datos e Inteligencia Artificial', 3, 1, 'ING-DATOS'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-DATOS'),
('MAT102', N'Álgebra Lineal para Ciencia de Datos', 4, 1, 'ING-DATOS'),
('DAT102', N'Programación en Python y Algoritmos', 4, 1, 'ING-DATOS'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-DATOS'),
('ING101', N'Inglés I', 2, 1, 'ING-DATOS'),
('DAT201', N'Estructuras de Datos y Programación Avanzada', 4, 2, 'ING-DATOS'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-DATOS'),
('DAT202', N'Matemáticas Discretas y Lógica Computacional', 3, 2, 'ING-DATOS'),
('DAT203', N'Bases de Datos Relacionales y SQL Avanzado', 4, 2, 'ING-DATOS'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-DATOS'),
('DAT301', N'Probabilidad y Estadística Descriptiva e Inferencial', 4, 3, 'ING-DATOS'),
('MAT301', N'Cálculo Multivariado y Optimización', 3, 3, 'ING-DATOS'),
('DAT302', N'Adquisición, Limpieza y Transformación de Datos (ETL)', 4, 3, 'ING-DATOS'),
('DAT303', N'Bases de Datos NoSQL, Grafos y Distribuidas', 3, 3, 'ING-DATOS'),
('DAT304', N'Programación en R para Análisis de Datos', 3, 3, 'ING-DATOS'),
('DAT401', N'Análisis Exploratorio y Visualización Interactiva de Datos', 4, 4, 'ING-DATOS'),
('DAT402', N'Inferencia Estadística y Modelos Lineales', 4, 4, 'ING-DATOS'),
('DAT403', N'Arquitectura de Computadores y Computación de Alto Rendimiento (HPC)', 3, 4, 'ING-DATOS'),
('MAT401', N'Métodos Numéricos y Optimización Convexa', 3, 4, 'ING-DATOS'),
('EST501', N'Modelos Estadísticos Multivariados', 3, 4, 'ING-DATOS'),
('DAT501', N'Machine Learning Supervisado (Modelos Predictivos)', 4, 5, 'ING-DATOS'),
('DAT502', N'Ingeniería de Datos y Pipelines (Airflow, Kafka)', 4, 5, 'ING-DATOS'),
('DAT503', N'Minería de Textos y Procesamiento de Lenguaje Natural (NLP)', 4, 5, 'ING-DATOS'),
('DAT504', N'Sistemas de Almacenamiento Masivo (Data Lakes y Data Warehouses)', 3, 5, 'ING-DATOS'),
('ECO601', N'Ingeniería Económica y Finanzas Digitales', 3, 5, 'ING-DATOS'),
('DAT601', N'Machine Learning No Supervisado y Reconocimiento de Patrones', 4, 6, 'ING-DATOS'),
('DAT602', N'Procesamiento de Big Data en la Nube (Spark, Hadoop)', 4, 6, 'ING-DATOS'),
('DAT603', N'Deep Learning y Redes Neuronales Artificiales', 4, 6, 'ING-DATOS'),
('DAT604', N'Series Temporales y Analítica Predictiva', 3, 6, 'ING-DATOS'),
('DAT605', N'Calidad y Gobierno del Dato (Data Governance)', 3, 6, 'ING-DATOS'),
('DAT701', N'Visión por Computador y Modelos Generativos', 4, 7, 'ING-DATOS'),
('DAT702', N'Despliegue y Operación de Modelos de ML (MLOps)', 4, 7, 'ING-DATOS'),
('DAT703', N'Analítica de Negocios y Business Intelligence (BI)', 3, 7, 'ING-DATOS'),
('DAT704', N'Electiva de Profundización I - Ciencia de Datos', 3, 7, 'ING-DATOS'),
('HUM701', N'Privacidad, Ética del Dato y Legislación de IA (GDPR)', 2, 7, 'ING-DATOS'),
('DAT801', N'Sistemas de Recomendación y Grafos de Conocimiento', 4, 8, 'ING-DATOS'),
('DAT802', N'Modelos de Lenguaje Grande (LLMs) e IA Generativa', 4, 8, 'ING-DATOS'),
('DAT803', N'Ciberseguridad y Protección de Datos', 3, 8, 'ING-DATOS'),
('DAT804', N'Electiva de Profundización II - Ciencia de Datos', 3, 8, 'ING-DATOS'),
('HUM801', N'Formulación y Gestión de Proyectos de Ciencia de Datos', 3, 8, 'ING-DATOS'),
('DAT901', N'Proyecto de Grado I - Ciencia de Datos', 4, 9, 'ING-DATOS'),
('DAT902', N'Simulación, Teoría de Juegos y Modelos de Decisión', 3, 9, 'ING-DATOS'),
('DAT903', N'Electiva de Profundización III - Ciencia de Datos', 3, 9, 'ING-DATOS'),
('DAT904', N'Electiva Complementaria de Humanidades', 2, 9, 'ING-DATOS'),
('DAT1001', N'Proyecto de Grado II - Ciencia de Datos', 4, 10, 'ING-DATOS'),
('DAT1002', N'Práctica Profesional en Ciencia de Datos', 6, 10, 'ING-DATOS'),
('DAT1003', N'Emprendimiento de Base Tecnológica en Datos e IA', 3, 10, 'ING-DATOS');

-- ======================================================================
-- PROGRAMA: Ingeniería Energética (ING-ENERG) - Total: 48 asignaturas
-- ======================================================================
INSERT INTO #TempMallas (Codigo, Nombre, Creditos, Semestre, CodigoPrograma) VALUES
('ENE101', N'Introducción a la Ingeniería Energética y Sostenibilidad', 3, 1, 'ING-ENERG'),
('MAT101', N'Cálculo Diferencial', 4, 1, 'ING-ENERG'),
('MAT102', N'Álgebra Lineal', 3, 1, 'ING-ENERG'),
('QUI101', N'Química General e Inorgánica', 3, 1, 'ING-ENERG'),
('ENE102', N'Dibujo Técnico y CAD Energético', 3, 1, 'ING-ENERG'),
('HUM101', N'Competencias Comunicativas', 2, 1, 'ING-ENERG'),
('ENE201', N'Termodinámica Clásica I', 4, 2, 'ING-ENERG'),
('MAT201', N'Cálculo Integral', 4, 2, 'ING-ENERG'),
('FIS201', N'Física Mecánica y Oscilaciones', 4, 2, 'ING-ENERG'),
('ENE202', N'Circuitos Eléctricos y Mediciones', 4, 2, 'ING-ENERG'),
('HUM201', N'Cátedra Universitaria Unimagdalena', 2, 2, 'ING-ENERG'),
('ENE301', N'Termodinámica Clásica II y Ciclos de Potencia', 4, 3, 'ING-ENERG'),
('ENE302', N'Mecánica de Fluidos Energéticos', 4, 3, 'ING-ENERG'),
('MAT301', N'Cálculo Multivariado', 3, 3, 'ING-ENERG'),
('FIS301', N'Electromagnetismo y Máquinas Eléctricas', 4, 3, 'ING-ENERG'),
('EST301', N'Estadística Aplicada a Sistemas Energéticos', 3, 3, 'ING-ENERG'),
('ENE401', N'Transferencia de Calor y Masa', 4, 4, 'ING-ENERG'),
('ENE402', N'Generación y Conversión de Energía Eléctrica', 4, 4, 'ING-ENERG'),
('MAT401', N'Ecuaciones Diferenciales y Modelado', 3, 4, 'ING-ENERG'),
('ENE403', N'Recursos Energéticos Fósiles y de Transición', 3, 4, 'ING-ENERG'),
('ENE404', N'Instrumentación y Sensores en Plantas Energéticas', 3, 4, 'ING-ENERG'),
('ENE501', N'Energía Solar Fotovoltaica y Térmica', 4, 5, 'ING-ENERG'),
('ENE502', N'Turbomaquinaria y Centrales Hidroeléctricas', 4, 5, 'ING-ENERG'),
('ENE503', N'Combustión, Biomasa y Biocombustibles', 4, 5, 'ING-ENERG'),
('ENE504', N'Redes de Distribución y Subestaciones Eléctricas', 3, 5, 'ING-ENERG'),
('ECO601', N'Ingeniería Económica y Mercados de Energía', 3, 5, 'ING-ENERG'),
('ENE601', N'Energía Eólica y Aerogeneradores', 4, 6, 'ING-ENERG'),
('ENE602', N'Eficiencia Energética y Auditorías (ISO 50001)', 4, 6, 'ING-ENERG'),
('ENE603', N'Sistemas de Almacenamiento de Energía y Baterías', 4, 6, 'ING-ENERG'),
('ENE604', N'Refrigeración, Climatización (HVAC) y Bombas de Calor', 3, 6, 'ING-ENERG'),
('ENE605', N'Modelación y Simulación de Sistemas Energéticos', 3, 6, 'ING-ENERG'),
('ENE701', N'Redes Eléctricas Inteligentes (Smart Grids) y Microredes', 4, 7, 'ING-ENERG'),
('ENE702', N'Hidrógeno Verde, Celdas de Combustible y PtX', 4, 7, 'ING-ENERG'),
('ENE703', N'Impacto Ambiental y Descarbonización Industrial', 3, 7, 'ING-ENERG'),
('ENE704', N'Electiva de Profundización I - Energética', 3, 7, 'ING-ENERG'),
('HUM701', N'Regulación y Marco Legal del Sector Eléctrico y Energético', 2, 7, 'ING-ENERG'),
('ENE801', N'Geotermia y Otras Energías No Convencionales', 4, 8, 'ING-ENERG'),
('ENE802', N'Generación Distribuida y Autoconsumo Industrial', 4, 8, 'ING-ENERG'),
('ENE803', N'Gestión de la Demanda y Movilidad Eléctrica', 3, 8, 'ING-ENERG'),
('ENE804', N'Electiva de Profundización II - Energética', 3, 8, 'ING-ENERG'),
('HUM801', N'Formulación y Evaluación de Proyectos Energéticos', 3, 8, 'ING-ENERG'),
('ENE901', N'Proyecto de Grado I - Energética', 4, 9, 'ING-ENERG'),
('ENE902', N'Mercado Eléctrico Mayorista y Transición Energética Justa', 3, 9, 'ING-ENERG'),
('ENE903', N'Electiva de Profundización III - Energética', 3, 9, 'ING-ENERG'),
('HUM901', N'Ética Profesional y Gobernanza Energética', 2, 9, 'ING-ENERG'),
('ENE1001', N'Proyecto de Grado II - Energética', 4, 10, 'ING-ENERG'),
('ENE1002', N'Práctica Profesional en Ingeniería Energética', 6, 10, 'ING-ENERG'),
('ENE1003', N'Emprendimiento e Innovación en Soluciones Climáticas', 3, 10, 'ING-ENERG');

-- 4. Realizar MERGE en la tabla Asignaturas vinculando con el Programa Académico correspondiente
MERGE INTO [Asignaturas] AS Target
USING (
    SELECT 
        t.Codigo,
        t.Nombre,
        t.Creditos,
        t.Semestre,
        p.Id AS ProgramaAcademicoId
    FROM #TempMallas t
    INNER JOIN [ProgramasAcademicos] p ON p.Codigo = t.CodigoPrograma
) AS Source
ON (Target.[Codigo] = Source.[Codigo] AND Target.[ProgramaAcademicoId] = Source.[ProgramaAcademicoId])
WHEN MATCHED THEN
    UPDATE SET 
        Target.[Nombre] = Source.[Nombre],
        Target.[Creditos] = Source.[Creditos],
        Target.[Semestre] = Source.[Semestre],
        Target.[EstaActivo] = 1
WHEN NOT MATCHED THEN
    INSERT ([Id], [Codigo], [Nombre], [Creditos], [Semestre], [ProgramaAcademicoId], [FechaCreacion], [EstaActivo])
    VALUES (NEWID(), Source.[Codigo], Source.[Nombre], Source.[Creditos], Source.[Semestre], Source.[ProgramaAcademicoId], GETUTCDATE(), 1);

DROP TABLE #TempMallas;
GO

PRINT '======================================================================';
PRINT '  CARGA COMPLETA EXITOSA: Mallas curriculares de 10 programas cargadas'; 
PRINT '======================================================================';
GO