// <auto-generated />
using System;
using AssessmentSystem.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace assessment.DataAccess.Migrations
{
    [DbContext(typeof(ContextoAplicacionDb))]
    [Migration("20260824153643_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Asignatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.AsignaturaPlanAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LiderCalidadRaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("MetaLogroPorcentaje")
                        .HasColumnType("float");

                    b.Property<Guid>("PlanAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResultadoAprendizajeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RolEvaluacion")
                        .HasColumnType("int");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("LiderCalidadRaId");

                    b.HasIndex("ResultadoAprendizajeId");

                    b.HasIndex("PlanAssessmentId", "ResultadoAprendizajeId", "RolEvaluacion")
                        .IsUnique();

                    b.ToTable("AsignaturasPlanAssessment", (string)null);
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("TamanoArchivoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UriBlob")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MedicionId");

                    b.ToTable("Evidencias", (string)null);
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.IndicadorDesempeno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsignaturaPlanAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaPlanAssessmentId");

                    b.ToTable("IndicadoresDesempeno", (string)null);
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Medicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalisisCualitativo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("AsignaturaPlanAssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadNivel0a59")
                        .HasColumnType("int");

                    b.Property<int>("CantidadNivel60a69")
                        .HasColumnType("int");

                    b.Property<int>("CantidadNivel70a89")
                        .HasColumnType("int");

                    b.Property<int>("CantidadNivel90a100")
                        .HasColumnType("int");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionesRevision")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PlanMejora")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("TotalEstudiantesEvaluados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaPlanAssessmentId")
                        .IsUnique();

                    b.ToTable("Mediciones", (string)null);
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.PeriodoAcademico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActual")
                        .HasColumnType("bit");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PeriodosAcademicos");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.PlanAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LiderProgramaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodoAcademicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LiderProgramaId");

                    b.HasIndex("PeriodoAcademicoId")
                        .IsUnique();

                    b.ToTable("PlanesAssessment", (string)null);
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.ResultadoAprendizaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResultadosAprendizaje");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.AsignaturaPlanAssessment", b =>
                {
                    b.HasOne("AssessmentSystem.Core.Entities.Asignatura", "Asignatura")
                        .WithMany("AsignaturasPlan")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssessmentSystem.Core.Entities.Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssessmentSystem.Core.Entities.Usuario", "LiderCalidadRa")
                        .WithMany()
                        .HasForeignKey("LiderCalidadRaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssessmentSystem.Core.Entities.PlanAssessment", "PlanAssessment")
                        .WithMany("AsignaturasPlan")
                        .HasForeignKey("PlanAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssessmentSystem.Core.Entities.ResultadoAprendizaje", "ResultadoAprendizaje")
                        .WithMany("AsignaturasPlan")
                        .HasForeignKey("ResultadoAprendizajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");

                    b.Navigation("LiderCalidadRa");

                    b.Navigation("PlanAssessment");

                    b.Navigation("ResultadoAprendizaje");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Evidencia", b =>
                {
                    b.HasOne("AssessmentSystem.Core.Entities.Medicion", "Medicion")
                        .WithMany("Evidencias")
                        .HasForeignKey("MedicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicion");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.IndicadorDesempeno", b =>
                {
                    b.HasOne("AssessmentSystem.Core.Entities.AsignaturaPlanAssessment", "AsignaturaPlanAssessment")
                        .WithMany("IndicadoresDesempeno")
                        .HasForeignKey("AsignaturaPlanAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignaturaPlanAssessment");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Medicion", b =>
                {
                    b.HasOne("AssessmentSystem.Core.Entities.AsignaturaPlanAssessment", "AsignaturaPlanAssessment")
                        .WithOne("Medicion")
                        .HasForeignKey("AssessmentSystem.Core.Entities.Medicion", "AsignaturaPlanAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignaturaPlanAssessment");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.PlanAssessment", b =>
                {
                    b.HasOne("AssessmentSystem.Core.Entities.Usuario", "LiderPrograma")
                        .WithMany()
                        .HasForeignKey("LiderProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssessmentSystem.Core.Entities.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany("PlanesAssessment")
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LiderPrograma");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Usuario", b =>
                {
                    b.HasOne("AssessmentSystem.Core.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Asignatura", b =>
                {
                    b.Navigation("AsignaturasPlan");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.AsignaturaPlanAssessment", b =>
                {
                    b.Navigation("IndicadoresDesempeno");

                    b.Navigation("Medicion");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Medicion", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.PeriodoAcademico", b =>
                {
                    b.Navigation("PlanesAssessment");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.PlanAssessment", b =>
                {
                    b.Navigation("AsignaturasPlan");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.ResultadoAprendizaje", b =>
                {
                    b.Navigation("AsignaturasPlan");
                });

            modelBuilder.Entity("AssessmentSystem.Core.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
